name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

permissions:
  contents: write # Needed for uploading release assets and creating releases
  packages: write # Needed for uploading artifacts
  actions: read # Needed to read actions/checkout@v3 and other actions

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64, 386]
        include:
          - os: ubuntu-24.04
            goos: linux
            goarch: amd64
            extension: ""
          - os: ubuntu-24.04
            goos: linux
            goarch: arm64
            extension: ""
          - os: ubuntu-24.04
            goos: linux
            goarch: 386
            extension: ""
          - os: macos-latest
            goos: darwin
            goarch: amd64
            extension: ""
          - os: macos-latest
            goos: darwin
            goarch: arm64
            extension: ""
          - os: windows-latest
            goos: windows
            goarch: amd64
            extension: ".exe"
          - os: windows-latest
            goos: windows
            goarch: arm64
            extension: ".exe"
          - os: windows-latest
            goos: windows
            goarch: 386
            extension: ".exe"
        exclude:
          - os: ubuntu-24.04
            goos: darwin
          - os: ubuntu-24.04
            goos: windows
          - os: macos-latest
            goos: linux
          - os: macos-latest
            goos: windows
          - os: macos-latest
            goarch: 386
          - os: windows-latest
            goos: linux
          - os: windows-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Or your target Go version

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o senk-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: senk-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}
          path: senk-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit Messages
        id: get_commit_messages
        run: |
          # Fetch the previous tag
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          if [ -z "$previous_tag" ]; then
            # No previous tag found, use initial commit
            commits=$(git log --pretty=format:"%h %s")
          else
            # Get the list of commits between the previous tag and the current tag
            commits=$(git log --pretty=format:"%h %s" $previous_tag..HEAD)
          fi
          echo "commits<<EOF" >> $GITHUB_ENV
          echo "$commits" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ github.ref }} \
            ./senk-linux-amd64/senk-linux-amd64 \
            ./senk-linux-arm64/senk-linux-arm64 \
            ./senk-linux-386/senk-linux-386 \
            ./senk-darwin-amd64/senk-darwin-amd64 \
            ./senk-darwin-arm64/senk-darwin-arm64 \
            ./senk-windows-amd64.exe/senk-windows-amd64.exe \
            ./senk-windows-arm64.exe/senk-windows-arm64.exe \
            ./senk-windows-386.exe/senk-windows-386.exe \
            --title "Release ${{ github.ref }}" --notes "$commits"
